# Generated by Django 5.1.2 on 2024-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kino', '0004_movie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status_movie',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='Pro', max_length=50),
        ),
    ]
