# Generated by Django 5.1.2 on 2024-11-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kino', '0005_alter_movie_status_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=10, null=True),
        ),
    ]
